### ISSUE TITLE
Support truncating tables with foreign keys

### ISSUE THREAD

**Issue by Seldaek** [doctrine/data-fixtures#113]
I had to override the loadFixtures method of the LiipFunctionalTestBundle with this stuff to avoid blowing up mysql:

```
    protected function loadFixtures(array $classNames, $omName = null, $registryName = 'doctrine', $purgeMode = null)
    {
        $conn = $this->getContainer()->get($registryName)->getManager()->getConnection();
        $db = $conn->getDriver()->getDatabasePlatform()->getName();
        if ($db === 'mysql') {
            $conn->exec('SET FOREIGN_KEY_CHECKS=0');
        }
        $res = parent::loadFixtures($classNames, $omName, $registryName, $purgeMode);
        if ($db === 'mysql') {
            $conn->exec('SET FOREIGN_KEY_CHECKS=1');
        }

        return $res;
    }
```

Now obviously it could be integrated in the bundle (cc @lsmith77) but ideally it would be part of this library itself so everyone benefits. Not sure how/where to best do this though, so I'm dropping this here hoping someone will pick it up :)

**Comment by theofidry** [comment]
+1

**Comment by fschaeffer** [comment]
The only way to fiddle with this issue (as both MySQL won't fix it nor doctrine DBAL willing to add another vendor specific rule) for me was to create a special DBAL driver and use this during fixture loading.

https://coderwall.com/p/staybw/workaround-for-1701-cannot-truncate-a-table-referenced-in-a-foreign-key-constraint-using-doctrine-fixtures-load-purge-with-truncate gives some hints.

In Symfony I ended up using a config_fixtures.yml, passing the doctrine:fixtures:load env=fixtures where this special Driver is used

config_fixtures.yml
```yaml
...
doctrine: 
    dbal: 
        driver_class: AppBundle\DBAL\Driver
```

Driver.php
```php
<?php

namespace AppBundle\DBAL;

use Doctrine\DBAL\Driver\PDOMySql\Driver as BaseDriver;

class Driver extends BaseDriver
{
    /**
     * {@inheritdoc}
     */
    public function getDatabasePlatform()
    {
        return new Platform();
    }
}
```
Platform.php
```php
<?php

namespace AppBundle\DBAL;

use Doctrine\DBAL\Platforms\MySqlPlatform;

class Platform extends MySqlPlatform
{
    /**
     * {@inheritdoc}
     */
    public function getTruncateTableSQL($tableName, $cascade = false)
    {
        return sprintf('SET foreign_key_checks = 0;TRUNCATE %s;SET foreign_key_checks = 1;', $tableName);
    }
}
```

**Comment by Soullivaneuh** [comment]
@fschaeffer With your workaround, I get the following error:

```
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "driver_class" under "doctrine.dbal"                       
 ```

My doctrine dbal config:

```yml
doctrine:
    dbal:
        driver_class: AppBundle\DBAL\Driver
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

            powerdns:
                driver:   pdo_mysql
                host:     "%powerdns_host%"
                port:     "%powerdns_port%"
                dbname:   "%powerdns_name%"
                user:     "%powerdns_user%"
                password: "%powerdns_password%"
                charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
```

Any idea?

**Comment by Soullivaneuh** [comment]
Ok I get it, it's because I have multiple connections definitions. I have to specify it on each connection:

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver_class: AppBundle\DBAL\Driver
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
```
