### ISSUE TITLE
SQLite database tables list in tests for ORMPurger

### ISSUE THREAD

**Issue by BonBonSlick** [doctrine/data-fixtures#305]
|    Q        |   A
|------------ | -----
| Version     | "^2.5.11",

### Support Question

Trying to optimize tests. 
http://lzakrzewski.com/2016/02/tricks-to-speed-up-database-tests/

But cant purge database because ORMPurger throws exception that tables does not exist.
```
 dump($conn->exec('SELECT * FROM sqlite_master WHERE type = "table"')); // 0
// SQLite does not support that feature,tables  list 
 dump($this->getEntityManager()->getConnection()->getSchemaManager()->listDatabases()); 

```
settings
```
doctrine:
  dbal:
    driver: pdo_sqlite
    path: /tmp/test-test.db
    memory: true
    charset: UTF8
```

Dropping and creating schema works, but this is taking too much, 10-15 secs with fixtures loading. 1 test takes about 30 secs. 

How to get tables or do purge without recreation of schema? 
This way I can also do backup as described 

> Trick no 4: Restore cached copy of database
in link
